### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by DeepDetector** [hongshuochen/DefakeHop#3]
Hey,thanks for your great work!I have some question about experiment dataset.
Do you train on celeb train set and test on celeb test set?or  train on FF++ train set and test on celeb test set?
Best wish!

**Comment by hongshuochen** [comment]
Great question! We train and test our model on the same dataset!

**Comment by woo2020** [comment]
Hey,I don't find the data about  FF++(C23,C40) and Celeb(C23,C40).
Can you provide this data？
Thanks!
